/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ui;

import com.edusys.DAO.nhanVienDAO;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author ACER
 */
public class DoiMK_JF extends javax.swing.JFrame {

    nhanVienDAO nvDAO = new nhanVienDAO();

    /**
     * Creates new form DoiMKJframe
     */
    public DoiMK_JF() {
        initComponents();
        setLocationRelativeTo(null);
        txtTenNV.setText(Auth.user.getMaNV());
        txtTenNV.setEditable(false);
        txtTenNV.setBackground(Color.white);
    }

    void opendoiMatKhau() {
        try {
            String matKhau = new String(txtMatKhau.getPassword());
            String matKhauMoi = new String(txtMatKhauMoi.getPassword());
            String xacNhanMKM = new String(txtXacNhanMKM.getPassword());
            
            if (!matKhau.equals(Auth.user.getMatKhau())) {
                MsgBox.alert(this, "Sai mật khẩu hiện tại!");
            } else if (!matKhauMoi.equals(xacNhanMKM)) {
                MsgBox.alert(this, "Xác nhận mật khẩu không đúng!");
            } else {
                Auth.user.setMatKhau(matKhauMoi);
                nvDAO.update(Auth.user);
                MsgBox.alert(this, "Đổi mật khẩu thành công!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnDongY = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtXacNhanMKM = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblIcon = new javax.swing.JLabel();
        lblshow = new javax.swing.JLabel();
        lblhide = new javax.swing.JLabel();
        lblIcon1 = new javax.swing.JLabel();
        lblshow1 = new javax.swing.JLabel();
        lblhide1 = new javax.swing.JLabel();
        lblIcon2 = new javax.swing.JLabel();
        lblshow2 = new javax.swing.JLabel();
        lblhide2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EduSys-Đổi mật khẩu");
        setBackground(new java.awt.Color(187, 187, 187));

        jPanel1.setBackground(new java.awt.Color(228, 246, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 112, 82));
        jLabel2.setText("Tài Khoản:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 144, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-user.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 175, -1, -1));

        txtTenNV.setBackground(new java.awt.Color(228, 246, 250));
        txtTenNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTenNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        jPanel1.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 178, 209, 39));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-users.png"))); // NOI18N
        jLabel1.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 29, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("Mật khẩu:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 144, -1, -1));

        txtMatKhau.setBackground(new java.awt.Color(228, 246, 250));
        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        jPanel1.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 178, 170, 39));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Xác nhận mật khẩu mới");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 264, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 112, 82));
        jLabel4.setText("Mật khẩu mới:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 264, -1, -1));

        btnDongY.setBackground(new java.awt.Color(0, 76, 76));
        btnDongY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDongY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-update.png"))); // NOI18N
        btnDongY.setText("Đổi Mật Khẩu");
        btnDongY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongYActionPerformed(evt);
            }
        });
        jPanel1.add(btnDongY, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 396, -1, 41));

        btnHuy.setBackground(new java.awt.Color(0, 76, 76));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-back.png"))); // NOI18N
        btnHuy.setText("Quay Lại");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 399, -1, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 20));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 260, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-password.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 307, 43, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-password.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 307, 43, -1));

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 260, 20));

        txtMatKhauMoi.setBackground(new java.awt.Color(228, 246, 250));
        txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        jPanel1.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 310, 170, 39));

        txtXacNhanMKM.setBackground(new java.awt.Color(228, 246, 250));
        txtXacNhanMKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtXacNhanMKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        jPanel1.add(txtXacNhanMKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 310, 160, 39));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-key.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 175, 45, -1));

        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 260, 20));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"))); // NOI18N
        jPanel1.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        lblshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshowMouseClicked(evt);
            }
        });
        jPanel1.add(lblshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 40, 20));

        lblhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhideMouseClicked(evt);
            }
        });
        jPanel1.add(lblhide, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 40, 20));

        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"))); // NOI18N
        jPanel1.add(lblIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        lblshow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshow1MouseClicked(evt);
            }
        });
        jPanel1.add(lblshow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, 20));

        lblhide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhide1MouseClicked(evt);
            }
        });
        jPanel1.add(lblhide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 40, 20));

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"))); // NOI18N
        jPanel1.add(lblIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, -1, -1));

        lblshow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshow2MouseClicked(evt);
            }
        });
        jPanel1.add(lblshow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 40, 20));

        lblhide2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblhide2MouseClicked(evt);
            }
        });
        jPanel1.add(lblhide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongYActionPerformed
        if (Auth.checkNullPass(txtMatKhau)
                && Auth.checkNullPass(txtMatKhauMoi)
                && Auth.checkNullPass(txtXacNhanMKM)) {
            this.opendoiMatKhau();
        }
    }//GEN-LAST:event_btnDongYActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void lblhideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhideMouseClicked
        lblshow.setVisible(true);
        lblshow.setEnabled(true);
        txtMatKhau.setEchoChar((char) 0);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-show.png"));
        lblIcon.setIcon(icon);
        lblhide.setVisible(false);
        lblhide.setEnabled(false);
    }//GEN-LAST:event_lblhideMouseClicked

    private void lblhide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhide1MouseClicked
        lblshow1.setVisible(true);
        lblshow1.setEnabled(true);
        txtMatKhauMoi.setEchoChar((char) 0);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-show.png"));
        lblIcon1.setIcon(icon);
        lblhide1.setVisible(false);
        lblhide1.setEnabled(false);
    }//GEN-LAST:event_lblhide1MouseClicked

    private void lblhide2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblhide2MouseClicked
        lblshow2.setVisible(true);
        lblshow2.setEnabled(true);
        txtXacNhanMKM.setEchoChar((char) 0);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-show.png"));
        lblIcon2.setIcon(icon);
        lblhide2.setVisible(false);
        lblhide2.setEnabled(false);
    }//GEN-LAST:event_lblhide2MouseClicked

    private void lblshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshowMouseClicked
        lblhide.setVisible(true);
        lblhide.setEnabled(true);
        txtMatKhau.setEchoChar((char) 8226);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"));
        lblIcon.setIcon(icon);
        lblshow.setVisible(false);
        lblshow.setEnabled(false);
    }//GEN-LAST:event_lblshowMouseClicked

    private void lblshow1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshow1MouseClicked
        lblhide1.setVisible(true);
        lblhide1.setEnabled(true);
        txtMatKhauMoi.setEchoChar((char) 8226);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"));
        lblIcon1.setIcon(icon);
        lblshow1.setVisible(false);
        lblshow1.setEnabled(false);
    }//GEN-LAST:event_lblshow1MouseClicked

    private void lblshow2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshow2MouseClicked
        lblhide2.setVisible(true);
        lblhide2.setEnabled(true);
        txtXacNhanMKM.setEchoChar((char) 8226);
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hide.png"));
        lblIcon2.setIcon(icon);
        lblshow2.setVisible(false);
        lblshow2.setEnabled(false);
    }//GEN-LAST:event_lblshow2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMK_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMK_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMK_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMK_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMK_JF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongY;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblhide;
    private javax.swing.JLabel lblhide1;
    private javax.swing.JLabel lblhide2;
    private javax.swing.JLabel lblshow;
    private javax.swing.JLabel lblshow1;
    private javax.swing.JLabel lblshow2;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JPasswordField txtXacNhanMKM;
    // End of variables declaration//GEN-END:variables
}
