/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.edusys.ui;

import com.edusys.DAO.nhanVienDAO;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author ACER
 */
public class ForgotJD extends javax.swing.JDialog {
    private final static Logger log = LogManager.getLogger(Mainn.class);
    int randomcode;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    public String user;
    
    public ForgotJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        PropertyConfigurator.configure("D:\\HK4\\DA_Mau\\DuAnMau\\EduSys\\test\\log4j.properties");
        setLocationRelativeTo(null);
        setIconImage(XImage.getAppIcon());
    }

    public ForgotJD(String username) {
        this.user = username;
        initComponents();
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEmailIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnXacNhan = new javax.swing.JButton();
        btnDoiMK = new javax.swing.JButton();
        lblEmail1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblEmailIcon1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtCapcha = new javax.swing.JTextField();
        btnGuiThu = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        lblEmailIcon2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblEmail3 = new javax.swing.JLabel();
        lblEmailIcon3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        btnCancel1 = new javax.swing.JButton();
        txtXacNhanMKM = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(228, 246, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 141, 120), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-mailing.png"))); // NOI18N
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 100, 100));

        lblEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(238, 112, 82));
        lblEmail.setText("Mã xác nhận:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, -1));

        lblEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-doimk1.png"))); // NOI18N
        jPanel1.add(lblEmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 50));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 280, 20));

        btnXacNhan.setBackground(new java.awt.Color(0, 95, 95));
        btnXacNhan.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Tick.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setBorder(null);
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel1.add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 130, 45));

        btnDoiMK.setBackground(new java.awt.Color(0, 95, 95));
        btnDoiMK.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnDoiMK.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-update.png"))); // NOI18N
        btnDoiMK.setText("Đổi Mật Khẩu");
        btnDoiMK.setBorder(null);
        btnDoiMK.setEnabled(false);
        btnDoiMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMKActionPerformed(evt);
            }
        });
        jPanel1.add(btnDoiMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 180, 45));

        lblEmail1.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblEmail1.setForeground(new java.awt.Color(238, 112, 82));
        lblEmail1.setText("Địa chỉ email:");
        jPanel1.add(lblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 120, -1));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 280, 20));

        lblEmailIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-email-sign.png"))); // NOI18N
        jPanel1.add(lblEmailIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 40));

        txtEmail.setBackground(new java.awt.Color(228, 246, 250));
        txtEmail.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(250, 105, 0));
        txtEmail.setText("quockkps31817@fpt.edu.vn");
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 280, 40));

        txtCapcha.setBackground(new java.awt.Color(228, 246, 250));
        txtCapcha.setFont(new java.awt.Font("Be Vietnam Pro", 1, 16)); // NOI18N
        txtCapcha.setForeground(new java.awt.Color(250, 105, 0));
        txtCapcha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        txtCapcha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCapchaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCapchaFocusLost(evt);
            }
        });
        jPanel1.add(txtCapcha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 270, 40));

        btnGuiThu.setBackground(new java.awt.Color(0, 95, 95));
        btnGuiThu.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnGuiThu.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-send.png"))); // NOI18N
        btnGuiThu.setText("Gửi thư");
        btnGuiThu.setBorder(null);
        btnGuiThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiThuActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuiThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 45));

        lblEmail2.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(238, 112, 82));
        lblEmail2.setText("Mật khẩu:");
        jPanel1.add(lblEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 120, -1));

        lblEmailIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-doimk1.png"))); // NOI18N
        jPanel1.add(lblEmailIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 50));

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 280, 20));

        lblEmail3.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(238, 112, 82));
        lblEmail3.setText("Xác nhận mật khẩu:");
        jPanel1.add(lblEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 180, -1));

        lblEmailIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-doimk1.png"))); // NOI18N
        jPanel1.add(lblEmailIcon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 50));

        jSeparator4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 280, 20));

        btnCancel1.setBackground(new java.awt.Color(0, 95, 95));
        btnCancel1.setFont(new java.awt.Font("Be Vietnam Pro", 1, 18)); // NOI18N
        btnCancel1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-back.png"))); // NOI18N
        btnCancel1.setText("Quay lại");
        btnCancel1.setBorder(null);
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 130, 45));

        txtXacNhanMKM.setBackground(new java.awt.Color(228, 246, 250));
        txtXacNhanMKM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtXacNhanMKM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        txtXacNhanMKM.setEnabled(false);
        jPanel1.add(txtXacNhanMKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 230, 39));

        txtMatKhauMoi.setBackground(new java.awt.Color(228, 246, 250));
        txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(228, 246, 250)));
        txtMatKhauMoi.setEnabled(false);
        jPanel1.add(txtMatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 230, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if (Auth.checkNullText(txtEmail) && Auth.checkNullText(txtCapcha)) {
            if (Integer.valueOf(txtCapcha.getText()) == randomcode) {
                txtMatKhauMoi.setEnabled(true);
                txtXacNhanMKM.setEnabled(true);
                btnDoiMK.setEnabled(true);
                MsgBox.alert(this, "Xác nhận thành công!!!");
                log.info(txtEmail.getText()+"Xac nhan ma "+randomcode+" thanh cong!!!");
            } else {
                MsgBox.alert(this, "Mã code không đúng!!!");
            }
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnDoiMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMKActionPerformed
        if (txtMatKhauMoi.getText().equals(txtXacNhanMKM.getText())) {
            try {
                String update = "UPDATE NhanVien SET MatKhau=? WHERE Email = ?";
                con = DriverManager.getConnection("jdbc:sqlserver://localhost;database=EduSys;user=sa;password=123");
                pst = con.prepareStatement(update);
                System.out.println(txtXacNhanMKM.getText());
                pst.setString(1, txtXacNhanMKM.getText());
                pst.setString(2, txtEmail.getText());
                pst.executeUpdate();
                System.out.println(pst);
                MsgBox.alert(this, "Đổi mật khẩu thành công");
//                dispose();
                log.info(txtEmail.getText()+"Doi mat khau thanh cong");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } 
        else {
            MsgBox.alert(this, "Đỗi mật khẩu không thành công");
        }
    }//GEN-LAST:event_btnDoiMKActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
//        if (txtEmail.getText().equalsIgnoreCase("Email...")) {
//            txtEmail.setText("");
//            txtEmail.setForeground(Color.black);
//        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
//        if (txtEmail.getText().equalsIgnoreCase("")) {
//            txtEmail.setText("Email...");
//            txtEmail.setForeground(Color.gray);
//        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtCapchaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapchaFocusGained
//        if (txtCapcha.getText().equalsIgnoreCase("Mã xác nhận...")) {
//            txtCapcha.setText("");
//            txtCapcha.setForeground(Color.black);
//        }
    }//GEN-LAST:event_txtCapchaFocusGained

    private void txtCapchaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCapchaFocusLost
//        if (txtCapcha.getText().equalsIgnoreCase("")) {
//            txtCapcha.setText("Mã xác nhận...");
//            txtCapcha.setForeground(Color.gray);
//        }
    }//GEN-LAST:event_txtCapchaFocusLost

    private void btnGuiThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiThuActionPerformed
        try {

            Random rand = new Random();
            randomcode = rand.nextInt(999999);
            String host = "smtp.gmail.com";
            String user = "kienquocpro00@gmail.com";
            String pass = "hsnsilnwtjlwxizc";
            String To = txtEmail.getText();
            String Subject = "Thong tin mat khau - EduSys";
            String message = "Mã code xác nhận lại mật khẩu:" + randomcode;
            boolean sessionDebug = false;
            Properties props = new Properties();
            props.put("mail.smtp.host", "smtp.gmail.com");
            props.put("mail.smtp.port", "587");
            props.put("mail.smtp.auth", "true");
            props.put("mail.smtp.ssl.trust", "smtp.gmail.com");
            props.put("mail.smtp.starttls.enable", "true");
            props.put("mail.smtp.starttls.required", "true");
            props.put("mail.smtp.host", "host");
            Session session = Session.getDefaultInstance(props, null);
            session.setDebug(sessionDebug);
            Message msg = new MimeMessage(session);

            msg.setFrom(new InternetAddress(user));
            InternetAddress[] address = {new InternetAddress(To)};
            msg.setRecipients(Message.RecipientType.TO, address);
            msg.setSubject(Subject);
            msg.setText(message);
            Transport tranport = session.getTransport("smtp");
            tranport.connect(host, user, pass);
            tranport.sendMessage(msg, msg.getAllRecipients());
            tranport.close();
            MsgBox.alert(null, "Gửi mã thành công vui lòng kiểm tra email");
            log.info(txtEmail.getText()+"Vua gui thanh cong ma thay doi email!!!");
        } catch (Exception e) {
            System.out.println(e);
            MsgBox.alert(null, "Gửi mã không thành công");
        }
    }//GEN-LAST:event_btnGuiThuActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        dispose();
        new DangNhapJD(null, true).setVisible(true);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForgotJD dialog = new ForgotJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDoiMK;
    private javax.swing.JButton btnGuiThu;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    private javax.swing.JLabel lblEmailIcon;
    private javax.swing.JLabel lblEmailIcon1;
    private javax.swing.JLabel lblEmailIcon2;
    private javax.swing.JLabel lblEmailIcon3;
    private javax.swing.JTextField txtCapcha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhanMKM;
    // End of variables declaration//GEN-END:variables

}
