/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ui;

import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.XImage;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;


public class Mainn extends javax.swing.JFrame {

    private final static Logger log = LogManager.getLogger(Mainn.class);

    public Mainn() {
        initComponents();
        PropertyConfigurator.configure("D:\\HK4\\DA_Mau\\DuAnMau\\EduSys\\test\\log4j.properties");
        setIconImage(XImage.getAppIcon());
        setLocationRelativeTo(null);
        this.openDongHo();
        this.openWelcome();
        this.openLogin();
    }

    private void openDongHo() {
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
        }).start();
    }

    private void openLogin() {
        new DangNhapJD(this, true).setVisible(true);
    }

    private void openWelcome() {
        new ChaoJD(this, true).setVisible(true);
    }

    public void logout() {
        Auth.clear();
        MsgBox.alert(this, "Bạn đã đăng xuất\nVui lòng đăng nhập để sử dụng!");
        new DangNhapJD(this, true).setVisible(true);
    }

    public void exit() {
        if (MsgBox.confirm(this, "Bạn có muốn kết thúc phiên làm việc không?")) {
            System.exit(0);
        }
    }

    /////////
    private void OpenNguoiHoc() {
        if (Auth.isLogin()) {
            new NguoiHocJF().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    private void OpenNhanVien() {
        if (Auth.isLogin()) {
            new NhanVienJF().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    private void OpenKhoaHoc() {
        if (Auth.isLogin()) {
            new KhoaHocJF().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    private void OpenChuyenDe() {
        if (Auth.isLogin()) {
            new ChuyenDe_JF().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    private void OpenHocVien() {
        if (Auth.isLogin()) {
            new HocVienJD(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    private void openThongKe(int index) {
        if (Auth.isLogin()) {
            if (index == 3 && !Auth.isManager()) {
                MsgBox.alert(this, "Chỉ trường phòng được xem chức năng này!");
                return;
            }
            ThongKeJF tk = new ThongKeJF();
            tk.selectTab(index);
            tk.setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    public void openGioiThieu() {
        new GioiThieuJD(this, true).setVisible(true);
    }

    public void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new java.io.File("help/index.html").toURI());
        } catch (Exception e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }

    public void openDoiMatKhau() {
        if (Auth.isLogin()) {
            new DoiMK_JF().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập để sử dụng!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnChuyenDe = new javax.swing.JButton();
        btnNguoiHoc = new javax.swing.JButton();
        btnKhoaHoc = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        lblTenNV = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mndangNhap = new javax.swing.JMenuItem();
        mndangXuat = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mndoiMatKhau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnketThuc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Menunguoihoc = new javax.swing.JMenuItem();
        MenuNhanVien = new javax.swing.JMenuItem();
        MenuKhoaHoc = new javax.swing.JMenuItem();
        MenuChuyenDe = new javax.swing.JMenuItem();
        mnHocVien = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnNHTN = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnDiemKH = new javax.swing.JMenuItem();
        mnDiemTungKhoa = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnDoanhThu = new javax.swing.JMenuItem();
        MenuHuongDan = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠP EDUSYS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(228, 141, 120));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/logo2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 101, 68));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Info.png"))); // NOI18N
        jLabel2.setText("Hệ quản lý đào tạo");

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(238, 101, 68));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Alarm.png"))); // NOI18N
        lblDongHo.setText("00:00:00 PM");

        jPanel1.setBackground(new java.awt.Color(228, 141, 120));

        btnDangXuat.setBackground(new java.awt.Color(0, 63, 63));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-dangxuat.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnKetThuc.setBackground(new java.awt.Color(0, 63, 63));
        btnKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKetThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-ketthuc.png"))); // NOI18N
        btnKetThuc.setText("Kết Thúc");
        btnKetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKetThuc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        btnChuyenDe.setBackground(new java.awt.Color(0, 63, 63));
        btnChuyenDe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-chuyende.png"))); // NOI18N
        btnChuyenDe.setText("Chuyên Đề");
        btnChuyenDe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChuyenDe.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnChuyenDe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChuyenDeActionPerformed(evt);
            }
        });

        btnNguoiHoc.setBackground(new java.awt.Color(0, 63, 63));
        btnNguoiHoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNguoiHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-nguoihoc.png"))); // NOI18N
        btnNguoiHoc.setText("Người Học");
        btnNguoiHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNguoiHoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNguoiHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNguoiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguoiHocActionPerformed(evt);
            }
        });

        btnKhoaHoc.setBackground(new java.awt.Color(0, 63, 63));
        btnKhoaHoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-khoahoc.png"))); // NOI18N
        btnKhoaHoc.setText("Khóa Học");
        btnKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhoaHoc.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnKhoaHoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaHocActionPerformed(evt);
            }
        });

        btnHuongDan.setBackground(new java.awt.Color(0, 63, 63));
        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnHuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-hocvien.png"))); // NOI18N
        btnHuongDan.setText("Học Viên");
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(0, 63, 63));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-nhanvien.png"))); // NOI18N
        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("Người Dùng:");

        lblVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVaiTro.setText("Chức Vụ:");

        btnThongKe.setBackground(new java.awt.Color(0, 63, 63));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/icons8-thongke.png"))); // NOI18N
        btnThongKe.setText("Thống Kê");
        btnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongKe.setMargin(new java.awt.Insets(2, 10, 2, 10));
        btnThongKe.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChuyenDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKhoaHoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuongDan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNguoiHoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThongKe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKetThuc)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(lblVaiTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTenNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVaiTro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKetThuc)
                            .addComponent(btnDangXuat)
                            .addComponent(btnChuyenDe)
                            .addComponent(btnNguoiHoc)
                            .addComponent(btnKhoaHoc)
                            .addComponent(btnHuongDan)
                            .addComponent(btnNhanVien)
                            .addComponent(btnThongKe))))
                .addGap(9, 9, 9))
        );

        jSeparator5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(228, 141, 120));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMenuBar1.setForeground(new java.awt.Color(238, 101, 68));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenu1.setForeground(new java.awt.Color(238, 101, 68));
        jMenu1.setText("Hệ Thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mndangNhap.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mndangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mndangNhap.setForeground(new java.awt.Color(238, 101, 68));
        mndangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Key.png"))); // NOI18N
        mndangNhap.setText("Đăng Nhập");
        mndangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndangNhapActionPerformed(evt);
            }
        });
        jMenu1.add(mndangNhap);

        mndangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mndangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mndangXuat.setForeground(new java.awt.Color(238, 101, 68));
        mndangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Log out.png"))); // NOI18N
        mndangXuat.setText("Đăng Xuất");
        mndangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mndangXuatMouseClicked(evt);
            }
        });
        mndangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(mndangXuat);
        jMenu1.add(jSeparator1);

        mndoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mndoiMatKhau.setForeground(new java.awt.Color(238, 101, 68));
        mndoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Refresh.png"))); // NOI18N
        mndoiMatKhau.setText("Đổi Mất Khẩu");
        mndoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mndoiMatKhauMouseClicked(evt);
            }
        });
        mndoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mndoiMatKhauActionPerformed(evt);
            }
        });
        jMenu1.add(mndoiMatKhau);
        jMenu1.add(jSeparator2);

        mnketThuc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        mnketThuc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnketThuc.setForeground(new java.awt.Color(238, 101, 68));
        mnketThuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Stop.png"))); // NOI18N
        mnketThuc.setText("Kết Thúc");
        mnketThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnketThucActionPerformed(evt);
            }
        });
        jMenu1.add(mnketThuc);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(238, 101, 68));
        jMenu2.setText("Quản Lý");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Menunguoihoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menunguoihoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Menunguoihoc.setForeground(new java.awt.Color(238, 101, 68));
        Menunguoihoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Conference.png"))); // NOI18N
        Menunguoihoc.setText("Người Học");
        Menunguoihoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenunguoihocActionPerformed(evt);
            }
        });
        jMenu2.add(Menunguoihoc);

        MenuNhanVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuNhanVien.setForeground(new java.awt.Color(238, 101, 68));
        MenuNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Lists.png"))); // NOI18N
        MenuNhanVien.setText("Nhân Viên");
        MenuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNhanVienActionPerformed(evt);
            }
        });
        jMenu2.add(MenuNhanVien);

        MenuKhoaHoc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuKhoaHoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuKhoaHoc.setForeground(new java.awt.Color(238, 101, 68));
        MenuKhoaHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Certificate.png"))); // NOI18N
        MenuKhoaHoc.setText("Khóa Học");
        MenuKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKhoaHocActionPerformed(evt);
            }
        });
        jMenu2.add(MenuKhoaHoc);

        MenuChuyenDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuChuyenDe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MenuChuyenDe.setForeground(new java.awt.Color(238, 101, 68));
        MenuChuyenDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/User group.png"))); // NOI18N
        MenuChuyenDe.setText("Chuyên Đề");
        MenuChuyenDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuChuyenDeActionPerformed(evt);
            }
        });
        jMenu2.add(MenuChuyenDe);

        mnHocVien.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnHocVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnHocVien.setForeground(new java.awt.Color(238, 101, 68));
        mnHocVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Boy.png"))); // NOI18N
        mnHocVien.setText("Học Viên");
        mnHocVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHocVienActionPerformed(evt);
            }
        });
        jMenu2.add(mnHocVien);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(238, 101, 68));
        jMenu3.setText("Thống Kê");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        mnNHTN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnNHTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnNHTN.setForeground(new java.awt.Color(238, 101, 68));
        mnNHTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Clien list.png"))); // NOI18N
        mnNHTN.setText("Người Học Từng Năm");
        mnNHTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnNHTNActionPerformed(evt);
            }
        });
        jMenu3.add(mnNHTN);
        jMenu3.add(jSeparator3);

        mnDiemKH.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDiemKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnDiemKH.setForeground(new java.awt.Color(238, 101, 68));
        mnDiemKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Card file.png"))); // NOI18N
        mnDiemKH.setText("Bảng Điểm Khóa Học");
        mnDiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemKHActionPerformed(evt);
            }
        });
        jMenu3.add(mnDiemKH);

        mnDiemTungKhoa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDiemTungKhoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnDiemTungKhoa.setForeground(new java.awt.Color(238, 101, 68));
        mnDiemTungKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Bar chart.png"))); // NOI18N
        mnDiemTungKhoa.setText("Điểm Từng Khóa");
        mnDiemTungKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemTungKhoaActionPerformed(evt);
            }
        });
        jMenu3.add(mnDiemTungKhoa);
        jMenu3.add(jSeparator4);

        mnDoanhThu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mnDoanhThu.setForeground(new java.awt.Color(238, 101, 68));
        mnDoanhThu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Dollar.png"))); // NOI18N
        mnDoanhThu.setText("Doanh Thu Chuyên Đề");
        mnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDoanhThuActionPerformed(evt);
            }
        });
        jMenu3.add(mnDoanhThu);

        jMenuBar1.add(jMenu3);

        MenuHuongDan.setForeground(new java.awt.Color(238, 101, 68));
        MenuHuongDan.setText("Trợ Giúp");
        MenuHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(238, 101, 68));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Globe.png"))); // NOI18N
        jMenuItem14.setText("Hướng Dẫn Sử Dụng");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        MenuHuongDan.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(238, 101, 68));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Brick house.png"))); // NOI18N
        jMenuItem15.setText("Giới Thiệu Sản Phẩm");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MenuHuongDan.add(jMenuItem15);

        jMenuBar1.add(MenuHuongDan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDongHo)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
            .addComponent(jSeparator5)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblDongHo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNguoiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguoiHocActionPerformed
        this.OpenNguoiHoc();
    }//GEN-LAST:event_btnNguoiHocActionPerformed

    private void btnChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChuyenDeActionPerformed
        this.OpenChuyenDe();
    }//GEN-LAST:event_btnChuyenDeActionPerformed

    private void btnKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaHocActionPerformed
        this.OpenKhoaHoc();
    }//GEN-LAST:event_btnKhoaHocActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.logout();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        this.exit();
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        this.OpenHocVien();
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        this.OpenNhanVien();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        new GioiThieuJD(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void mnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDoanhThuActionPerformed
        this.openThongKe(3);
    }//GEN-LAST:event_mnDoanhThuActionPerformed

    private void mnDiemTungKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemTungKhoaActionPerformed
        this.openThongKe(2);
    }//GEN-LAST:event_mnDiemTungKhoaActionPerformed

    private void mnDiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemKHActionPerformed
        this.openThongKe(1);
    }//GEN-LAST:event_mnDiemKHActionPerformed

    private void mnNHTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnNHTNActionPerformed
        this.openThongKe(0);
    }//GEN-LAST:event_mnNHTNActionPerformed

    private void mnHocVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHocVienActionPerformed
        this.OpenHocVien();
    }//GEN-LAST:event_mnHocVienActionPerformed

    private void MenuChuyenDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuChuyenDeActionPerformed
        this.OpenChuyenDe();
    }//GEN-LAST:event_MenuChuyenDeActionPerformed

    private void MenuKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKhoaHocActionPerformed
        this.OpenKhoaHoc();
    }//GEN-LAST:event_MenuKhoaHocActionPerformed

    private void MenuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNhanVienActionPerformed
        this.OpenNhanVien();
    }//GEN-LAST:event_MenuNhanVienActionPerformed

    private void MenunguoihocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenunguoihocActionPerformed
        this.OpenNguoiHoc();
    }//GEN-LAST:event_MenunguoihocActionPerformed

    private void mnketThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnketThucActionPerformed
        this.exit();
    }//GEN-LAST:event_mnketThucActionPerformed

    private void mndoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndoiMatKhauActionPerformed
        new DoiMK_JF().setVisible(true);
    }//GEN-LAST:event_mndoiMatKhauActionPerformed

    private void mndangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndangXuatActionPerformed
        this.logout();
    }//GEN-LAST:event_mndangXuatActionPerformed

    private void mndangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mndangNhapActionPerformed
        openLogin();
    }//GEN-LAST:event_mndangNhapActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        this.openThongKe(0);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void mndoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mndoiMatKhauMouseClicked

    }//GEN-LAST:event_mndoiMatKhauMouseClicked

    private void mndangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mndangXuatMouseClicked

    }//GEN-LAST:event_mndangXuatMouseClicked

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        this.openHuongDan();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lblTenNV.setText("Ngời dùng: " + Auth.user.getMaNV());
        lblVaiTro.setText("Chức vụ: " + String.valueOf(Auth.user.isVaiTro() ? "Trưởng Phòng" : "Nhân Viên"));
        log.info("Vai tro:"+String.valueOf(Auth.user.isVaiTro() ? "Truong Phong" : "Nhân Viên")+"--"+"Nguoi dung:"+Auth.user.getMaNV()+"--"+"Dang Nhap Thanh COng");

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuChuyenDe;
    private javax.swing.JMenu MenuHuongDan;
    private javax.swing.JMenuItem MenuKhoaHoc;
    private javax.swing.JMenuItem MenuNhanVien;
    private javax.swing.JMenuItem Menunguoihoc;
    private javax.swing.JButton btnChuyenDe;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnKhoaHoc;
    private javax.swing.JButton btnNguoiHoc;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem mnDiemKH;
    private javax.swing.JMenuItem mnDiemTungKhoa;
    private javax.swing.JMenuItem mnDoanhThu;
    private javax.swing.JMenuItem mnHocVien;
    private javax.swing.JMenuItem mnNHTN;
    private javax.swing.JMenuItem mndangNhap;
    private javax.swing.JMenuItem mndangXuat;
    private javax.swing.JMenuItem mndoiMatKhau;
    private javax.swing.JMenuItem mnketThuc;
    // End of variables declaration//GEN-END:variables

}
